// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QLBH.Data;

#nullable disable

namespace QLBH.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20240722013531_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QLBH.Models.Customer", b =>
                {
                    b.Property<int>("Cust_code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Cust_code"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cust_name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CUST_NAME123");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Update_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Updater")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Cust_code");

                    b.ToTable("CUSTOMER");
                });

            modelBuilder.Entity("QLBH.Models.Employee", b =>
                {
                    b.Property<int>("Emp_code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Emp_code"));

                    b.Property<int>("Dept_code")
                        .HasColumnType("int");

                    b.Property<string>("Emp_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Hire_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Update_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Updater")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Emp_code");

                    b.ToTable("EMPLOYEE");
                });

            modelBuilder.Entity("QLBH.Models.ORDER_DETAILS", b =>
                {
                    b.Property<int?>("SO_ROW_NO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("SO_ROW_NO"));

                    b.Property<float?>("CMP_TAX_RATE")
                        .HasColumnType("real");

                    b.Property<int?>("COMPLETE_FLG")
                        .HasColumnType("int");

                    b.Property<int?>("DELIVERED_QTY")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DELIVERY_DATE")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DELIVERY_ORDER_QTY")
                        .HasColumnType("int");

                    b.Property<float?>("DISCOUNT")
                        .HasColumnType("real");

                    b.Property<int?>("ORDER_NO")
                        .HasColumnType("int");

                    b.Property<int?>("PROD_CODE")
                        .HasColumnType("int");

                    b.Property<string>("PROD_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("QUANTITY")
                        .HasColumnType("int");

                    b.Property<int?>("RESERVE_QTY")
                        .HasColumnType("int");

                    b.Property<float?>("UNITPRICE")
                        .HasColumnType("real");

                    b.Property<string>("UPDATER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UPDATE_DATE")
                        .HasColumnType("datetime2");

                    b.HasKey("SO_ROW_NO");

                    b.ToTable("ORDER_DETAILS");
                });

            modelBuilder.Entity("QLBH.Models.Orders", b =>
                {
                    b.Property<int>("Order_no")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Order_no"));

                    b.Property<int>("CMP_tax")
                        .HasColumnType("int");

                    b.Property<int>("Cust_code")
                        .HasColumnType("int");

                    b.Property<int>("Cust_sub_no")
                        .HasColumnType("int");

                    b.Property<int>("Custorder_no")
                        .HasColumnType("int");

                    b.Property<int>("Dept_code")
                        .HasColumnType("int");

                    b.Property<int>("Emp_code")
                        .HasColumnType("int");

                    b.Property<DateTime>("Order_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Required_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Slip_comment")
                        .HasColumnType("int");

                    b.Property<DateTime>("Update_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Updater")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WH_code")
                        .HasColumnType("int");

                    b.HasKey("Order_no");

                    b.ToTable("ORDERS");
                });

            modelBuilder.Entity("QLBH.Models.Product", b =>
                {
                    b.Property<int?>("PROD_CODE")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("PROD_CODE"));

                    b.Property<string>("PROD_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("STOCK_QTY")
                        .HasColumnType("int");

                    b.Property<decimal?>("UNITPRICE")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UPDATER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UPDATE_DATE")
                        .HasColumnType("datetime2");

                    b.Property<int?>("WH_CODE")
                        .HasColumnType("int");

                    b.HasKey("PROD_CODE");

                    b.ToTable("PRODUCT");
                });
#pragma warning restore 612, 618
        }
    }
}
